### ISSUE TITLE
make backend_http_health_port not required 

### ISSUE THREAD

**Issue by Alexvianet** [cloudfoundry-incubator/haproxy-boshrelease#127]
<%- health_check_options = "port " + p("ha_proxy.backend_http_health_port").to_s -%>
broke my httpchk
```
backend http-routers
    mode http
    balance roundrobin
    option httpchk GET /v1/sys/health
    server node0 10.1.1.1:8200 check inter 1000 port 8200 ssl verify none
    server node1 10.1.1.2:8200 check inter 1000 port 8200 ssl verify none
    server node2 10.1.1.3:8200 check inter 1000 port 8200 ssl verify none

```

if i remove health_check_options it's works:

```
backend http-routers
    mode http
    balance roundrobin
    option httpchk GET /v1/sys/health
    server node0 10.1.1.1:8200 check inter 1000 ssl verify none
    server node1 10.1.1.2:8200 check inter 1000 ssl verify none
    server node2 10.1.1.3:8200 check inter 1000 ssl verify none

```

**Comment by geofffranks** [comment]
@Alexvianet Is this error happening because haproxy is using a http health check by default now, or because the health check is defaulting to a different port than what your backend was listening on?

e.g. backend-port 8200, health-check port defaulting to 8080, or does any default http health check cause issues?

**Comment by Alexvianet** [comment]
i use raw_config now, helps
