### ISSUE TITLE
hatop pretty please?

### ISSUE THREAD

**Issue by jhunt** [cloudfoundry-incubator/haproxy-boshrelease#153]
Hi,

We use this BOSH release in the Genesis Cloud Foundry Kit for folks who don't have access to an IaaS-provided load balancer (hardware, software, or otherwise), and have often found it helpful to see how the backends are doing via hatop (https://github.com/feurix/hatop)

We currently do this ad hoc by SSHing into the haproxy VMs, and doing something akin to this (we only run Ubuntu stemcells):

```
# apt-get update
# apt-get install -y python
# curl -LO https://raw.githubusercontent.com/feurix/hatop/master/bin/hatop
# chmod 0755 hatop
```

Is there any interest in bundling hatop (possibly as an optional job?) with this BOSH release so that we no longer have to do that?

**Comment by geofffranks** [comment]
Sure, an optional job sounds great for that. @christopherclark is there anything special that needs to be done to add hatop (looks to be GPLv3) to this release?

**Comment by christopherclark** [comment]
@geofffranks @jhunt 

 Let me confer, briefly, and get back to you next week. Apache 2 and GPLv3 have a [compatibility issue](https://www.apache.org/licenses/GPL-compatibility.html), but I don't **think** that issue would be problematic for bosh releases.    

This gives me some pause though:  
"This licensing incompatibility applies only when some Apache project software becomes a derivative work of some GPLv3 software, because then the Apache software would have to be distributed under GPLv3. This would be incompatible with ASF's requirement that all Apache software must be distributed under the Apache License 2.0.

We avoid GPLv3 software because merely linking to it is considered by the GPLv3 authors to create a derivative work."

**Comment by christopherclark** [comment]
Okay - this is fine. As a policy we do not limit licensing for bosh releases as we're only providing a method for deploying and managing the code. Thanks for checking! Feel free to proceed with this @geofffranks

**Comment by jhunt** [comment]
Woot woot thanks!
