### ISSUE TITLE
check port for tcp_backend

### ISSUE THREAD

**Issue by patsys** [cloudfoundry-incubator/haproxy-boshrelease#184]
This is a feature request.
I need to check a other port by an tcp backend, I have add a http-check with the ha_proxy.tcp_backend_config .

Use Case:
https://github.com/zalando/patroni/blob/master/haproxy.cfg

The postiton it must added is https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/master/jobs/haproxy/templates/haproxy.config.erb#L615

**Comment by domdom82** [comment]
hi @patsys I understand that you want to be able to specify different backend ports per IP, essentially because you are running two backends on one IP using localhost. This will be hard to do without a breaking change because existing deployments require the "IP-only" structure described in https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/master/jobs/haproxy/spec#L351

Question: Why don't you run your two backends on a bridge network like [docker bridge](https://docs.docker.com/network/bridge/)? You could connect both haproxy and the backends to the same bridge network on the local machine. 

I.e. 
```
docker network-create my-net
docker run -d haproxy ...
docker run -d backend1
docker run -d backend2

docker network connect my-net haproxy
docker network connect my-net backend1
docker network connect my-net backend2
```

Then you have two different IPs for localhost.

**Comment by patsys** [comment]
Hello @domdom82  this was only an example why I need to specify a other port for healt check with http. I have to vms not localhost as backend use the same port 8008, the rest of then config ist the same.

**Comment by patsys** [comment]
my haproxy properties look like this
```   
    consumes:
      tcp_backend: {}
    properties:
      ha_proxy:
        max_connections: 100
        client_timeout:  1800
        connect_timeout: 4
        server_timeout: 1800
        backend_port: 5432
        check_timeout: 5
        tcp_link_port: 5432
        **tcp_link_check_port: 8008**
        tcp_backend_config: |
          option httpchk
          http-check expect status 200
          default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions```

**tcp_link_check_port** does not exist at this moment

**Comment by domdom82** [comment]
Ah I see. So instead of this
```
    server node<%= index %> <%= ip %>:<%= backend_port %> <%= resolvers -%>check inter 1000 <%= backend_ssl %><%- if tcp_proxy["backend_servers_local"] && !tcp_proxy["backend_servers_local"].empty? && !tcp_proxy["backend_servers_local"].include?(ip) then -%> backup<%- end -%>
```

you want something like this

```
    server node<%= index %> <%= ip %>:<%= backend_port %> <%= resolvers -%>check port <%=backend_health_port -%> inter 1000 <%= backend_ssl %><%- if tcp_proxy["backend_servers_local"] && !tcp_proxy["backend_servers_local"].empty? && !tcp_proxy["backend_servers_local"].include?(ip) then -%> backup<%- end -%>
```

so a custom health port for the tcp backend?

**Comment by patsys** [comment]
Yes. It can be more optional look like this the backend_ssl that check port only exist when backend_health_port is set.

**Comment by domdom82** [comment]
hi @patsys I wrote a PR to add the feature. Can you [check](#186 ) it out and see if this is what you need?
