### ISSUE TITLE
Add links support

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-incubator/haproxy-boshrelease#55]
It would be nice if the haproxy-boshrelease would consume links [just like the haproxy from cf-release](https://github.com/cloudfoundry/cf-release/blob/master/jobs/haproxy/spec#L18-L25).

**Comment by lcacciagioni** [comment]
@rkoster Is the ssh port hardcoded in [here](https://github.com/cloudfoundry/cf-release/blob/master/jobs/haproxy/templates/haproxy.conf.erb#L92)? Is that right?

**Comment by geofffranks** [comment]
I'd like to keep this release cf-agnostic, since it's not always deployed in front of it. The equivalent of the router link should probably be something like `http_backend`, and consume the port to send backend requests to as well.

For the ssh-proxy, that typically goes in the tcp-backends section, though I'm not aware of any feature to have an arbitrary array of links being consumed to set up multiple tcp-backends. You could always make use of the `ssh-proxy.service.cf.internal` hostname as the backend server, or potentially we could add an arbitrary number (5? 10?) of tcp-backend links that get processed, though the links would likely need to include some sort of way to map to configuration saying what the frontend port is,  and ssl settings for the frontend/backend

**Comment by geofffranks** [comment]
Closed via #56
