### ISSUE TITLE
Forward X-Forwarded-Client-Cert only if mutual TLS was successful

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-incubator/haproxy-boshrelease#86]
We should force-omit the X-Forwarded-Client-Cert header from requests if the request did not come in via a mutual TLS connection so we can ensure downstream applications that the header came from a trusted source.

Currently the header is only added if available, but if a client provides it without using mtls, it would likely still go through to the backend.

**Comment by shalako** [comment]
@gfranks FWIW, we took the approach of keeping existing behavior (passthrough any header), and offered a config option to lock this down when client connection was mtls. It requires a property to support a string instead of a boolean. 
https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/gorouter/spec#L115-L125

More importantly, I'd recommend sanitizing the header when `client_cert: true`.

**Comment by geofffranks** [comment]
The gorouter behaviors for handling XFCC are now available in haproxy v9.0.0. haproxy's default behavior is the `sanitize_set` option.
